import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import logo from '../public/logo.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className='bg-darkColor text-whiteColor flex flex-col items-center p-5 h-dvh antialiased'>
        <Image src={logo} alt='logo' width={250}></Image>        
        {children}
        </body>
    </html>
  )
}
